

export interface Neutralscheme {
	ZONE_ID: string,
	NOISE_WORD: string,
	REF_KEY: string,
	MAKER_USER_ID: string,
	CHECKER_USER_ID: string,
	MAKER_USER_NM: string,
	CHECKER_USER_NM: string,
	MAKER_COMMENT: string,
	CHECKER_COMMENT: string,
	MAKER_DTTM: string,
	CHECKER_DTTM: string,
	MAKER_DATE: string,
	CHECKER_DATE: string,
	CHANGE_TYPE: string,
	UPDATE_VERSION: string,
	VALIDATION_STATUS: string,
	VALID_FROM_DTTM: string,
	VALID_TO_DTTM: string
};

export interface Bicscheme {
	ZONE_ID:string,
	BIC:string,
	BIC8:string,
	INSTITUTION_NAME:string,
	CITY:string,
	COUNTRY:string,
	WATCHLIST_NAME:string,
	UID_NO:string,
	WATCHLIST_TYPE:string,
	REF_KEY:string,
	MAKER_USER_ID:string,
	CHECKER_USER_ID:string,
	MAKER_USER_NM:string,
	CHECKER_USER_NM:string,
	MAKER_COMMENT:string,
	CHECKER_COMMENT:string,
	MAKER_DTTM:string,
	CHECKER_DTTM:string,
	MAKER_DATE:string,
	CHECKER_DATE:string,
	CHANGE_TYPE:string,
	UPDATE_VERSION:string,
	VALIDATION_STATUS:string,
	VALID_FROM_DTTM:string,
	VALID_TO_DTTM:string


};
export interface Interdefination {
 
    ZONE_ID: string,
    LIST_TYPE: string,
    LIST_CATEGORY: string,
    WATCHLIST_NAME: string,
    WATCHLIST_ID: string,
    REF_KEY: string,
    MAKER_USER_ID: string,
    CHECKER_USER_ID: string,
    MAKER_USER_NM: string,
    CHECKER_USER_NM: string,
    MAKER_COMMENT: string,
    CHECKER_COMMENT: string,
    MAKER_DTTM: string,
    CHECKER_DTTM: string,
    MAKER_DATE: string,
    CHECKER_DATE: string,
    CHANGE_TYPE: string,
    UPDATE_VERSION: string,
    VALIDATION_STATUS: string,
    VALID_FROM_DTTM: string,
    VALID_TO_DTTM: string,
    DELETE_FLG: string,
};


export interface sanctioned {
ZONE_ID: string,
ENTRY_TYPE: string,
SANCTIONED_CITY:string,
REF_KEY: string,
MAKER_USER_ID: string,
CHECKER_USER_ID: string,
MAKER_USER_NM: string,
CHECKER_USER_NM: string,
MAKER_COMMENT: string,
CHECKER_COMMENT: string,
MAKER_DTTM: string,
CHECKER_DTTM: string,
MAKER_DATE: string,
CHECKER_DATE: string,
CHANGE_TYPE: string,
UPDATE_VERSION: string,
VALIDATION_STATUS: string,
VALID_FROM_DTTM: string,
VALID_TO_DTTM: string,
};


export interface internalwatchlist {
	UID_SERIAL_NO: string,
	ZONE_ID : string,
	WATCHLIST_ID : string,
	WATCHLIST_NAME : string,
	CUSTOMER_NAME_ENGLISH : string,
	CUSTOMER_NAME_ARABIC :string,
	CUSTOMER_TYPE:string,
	CITY :string,
	CUSTOMER_ACCOUNT : string,
	DOB : string,
	RESIDENCE_COUNTRY : string,
	RESIDENCE_COUNTRY_FLAG: string,
	NATIONALITY : string,
	ID_NUMBER: string,
	ID_TYPE :string,
	KNOWN_AS_NAME_ENGLISH : string,
	KNOWN_AS_NAME_ARABIC : string,
	MOTHER_NAME : string,
	ADDRESS: string,
	REMARKS: string,
	CIN :string,
	NEW_PAN :string,
	SOURCE: string,
	CUSTOMER_STATUS : string,
	BRANCH : string,
	CUSTOMER_RISK_LEVEL : string,
	CUSTOMER_CREATE_DATE: string,
	CUST_RISK_LEVEL_UPDATE_DATE : string,
	POLITICALLY_EXPOSED: string,
	DETAILS_PROGRAMS: string,
	OTHERS_REMARKS : string,
	OTHERS_DATA_SOURCES : string,
	OTHERS_RELATED_TO : string,
	};



	export interface Highriskcountry {
	ZONE_ID: string,
	COUNTRY_CODE: string,
	COUNTRY_NAME: string,
	RISK_LEVEL: string,
	SANCTIONED_FLAG:string,
	REF_KEY: string,
	MAKER_USER_ID: string,
	CHECKER_USER_ID: string,
	MAKER_USER_NM: string,
	CHECKER_USER_NM: string,
	MAKER_COMMENT: string,
	CHECKER_COMMENT: string,
	MAKER_DTTM: string,
	CHECKER_DTTM: string,
	MAKER_DATE: string,
	CHECKER_DATE: string,
	CHANGE_TYPE: string,
	UPDATE_VERSION: string,
	VALIDATION_STATUS: string,
	VALID_FROM_DTTM: string,
	VALID_TO_DTTM: string,
	};

	export interface Zonevsglobal {
		ZONE_ID: string,
		PROGRAM_KEYWORD: string,
		PROGRAM_KEYWORD_DESC:string,
		REF_KEY: string,
		MAKER_USER_ID: string,
		CHECKER_USER_ID: string,
		MAKER_USER_NM: string,
		CHECKER_USER_NM: string,
		MAKER_COMMENT: string,
		CHECKER_COMMENT: string,
		MAKER_DTTM: string,
		CHECKER_DTTM: string,
		MAKER_DATE: string,
		CHECKER_DATE: string,
		CHANGE_TYPE: string,
		UPDATE_VERSION: string,
		VALIDATION_STATUS: string,
		VALID_FROM_DTTM: string,
		VALID_TO_DTTM: string,
		}